trigger:
  # branches:
  #   include:
  #   - master
  tags:
    include:
    - '*'

pool:
    vmImage: 'ubuntu-latest'
  
steps:
  # - script: echo Hello, world!
  #   displayName: 'Run a one-line script'

  # to install aws cli manually
  # the following two tasks are commented out because it's included in vmImage: 'ubuntu-latest'
  # see <https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md>
  #
  # - task: UsePythonVersion@0
  #   inputs:
  #     versionSpec: '3.6'
  #     architecture: 'x64'

  # - script: | 
  #     sudo pip3 install --upgrade pip
  #     pip3 install awscli --upgrade --user
  #     export PATH="/home/vsts/.local/bin:$PATH"
  #     echo $PATH
  #     aws --version
  #     which -a aws
  #     ls -alt /home/vsts/.local/bin/aws
  #     ls -alt /usr/local/bin/aws
  #     /home/vsts/.local/bin/aws --version
  #     /usr/local/bin/aws --version
  #   displayName: 'Install AWS CLI'
  #   env:
  #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
  #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

  - script: | 
      echo $AWS_ACCESS_KEY_ID
      chmod +x scripts/publish.sh
      ./scripts/publish.sh
#      export PATH="/home/vsts/.local/bin:$PATH"
    displayName: 'deploy'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)    
  