---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Creates a stack for a static website using CloudFormation and S3 plus CI/CD
  automation user to handle publishing workflow

Parameters:

  DomainName:
    Type: String
    Description: The domain name.
    Default: allthecloudbits.com

  DistributionOriginPath:
    Type: String
    Description: >
      The CloudFront distribution origin points to this prefix path within the
      website bucket
    Default: "/v0.0.1"

  SecretReferer:
    Type: String
    Description: >
      A secret Referer header set in the CloudFront distribution.  The S3
      bucket policy only alows requests that include this Referer value.
      This blocks direct requests to the S3 bucket website URL(s).
    Default: "79011a81-c048-4877-84f4-efe9577d7250"

  AutomationUserPassword:
    NoEcho: 'true'
    Type: String
    Description: automation user account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters

Tags:
  - Key: "Name"
    Value: "tagName"
  - Key: "Costcenter"
    Value: "tagCostcenter"
  - Key: "Division"
    Value: "tagDivision"
  - Key: "Environment"
    Value: "tagEnvironment"
  - Key: "Application"
    Value: "tagApplication"
  - Key: "Consumer"
    Value: "tagConsumer"

Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
        RoutingRules:
          - RedirectRule:
              HostName: !Sub "${DomainName}"
#              HttpRedirectCode: "307"
              Protocol: https
              ReplaceKeyWith: ""
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: "403"        
          - RedirectRule:
              HostName: !Sub "${DomainName}"
#              HttpRedirectCode: "307"
              Protocol: https
              ReplaceKeyWith: ""
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: "404"        


  CloudFrontLogsBucket:
    Type: "AWS::S3::Bucket"

  Cert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "*.${DomainName}"
      SubjectAlternativeNames:
        - !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          ValidationDomain: !Ref DomainName
      ValidationMethod: DNS

  WebsiteDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName   
          - !Sub "www.${DomainName}"   
        DefaultCacheBehavior:
          TargetOriginId: "WebsiteBucketOrigin"
          ViewerProtocolPolicy: "redirect-to-https"
          DefaultTTL: 600 # ten minutes
          MaxTTL: 600 # ten minutes
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
        DefaultRootObject: "index.html"
        Logging:
          IncludeCookies: "false"
          Bucket: !GetAtt CloudFrontLogsBucket.DomainName
          Prefix: "cloudfront/logs"
        Enabled: true
        PriceClass: "PriceClass_100" # "PriceClass_All"
        HttpVersion: "http2"
        ViewerCertificate:
#          CloudFrontDefaultCertificate: true
          AcmCertificateArn: !Ref Cert
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only          
        Origins:
          - Id: "WebsiteBucketOrigin"
            DomainName: !Sub "${S3BucketForWebsiteContent}.s3-website-${AWS::Region}.amazonaws.com"
            OriginPath: !Sub "${DistributionOriginPath}"
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'     
              OriginProtocolPolicy: 'http-only'       
            OriginCustomHeaders:
              - HeaderName: Referer
                HeaderValue: !Sub "${SecretReferer}"


          # - Id: "WebsiteBucketOrigin"
          #   DomainName: !Sub "${S3BucketForWebsiteContent}.s3-website-${AWS::Region}.amazonaws.com"
          #   OriginPath: !Sub "${DistributionOriginPath}"
          #   OriginCustomHeaders:
          #     - HeaderName: Referer
          #       HeaderValue: !Sub "${SecretReferer}"
          #   S3OriginConfig: {}
            #   OriginAccessIdentity:
            #     Fn::Join:
            #       - ""
            #       - - "origin-access-identity/cloudfront/"
            #         - Ref: "CloudFrontOriginAccessIdentity"
    DependsOn:
      - S3BucketForWebsiteContent
      - CloudFrontLogsBucket

  # CloudFrontOriginAccessIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: !Ref S3BucketForWebsiteContent

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketForWebsiteContent
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource: !Sub "${S3BucketForWebsiteContent.Arn}/*"
            Condition:
              StringLike:
                aws:Referer:
                  - !Sub "${SecretReferer}"
          # - Action:
          #     - s3:GetObject
          #   Effect: Deny
          #   Principal: "*"
          #   Resource: !Sub "${S3BucketForWebsiteContent.Arn}/*"
          #   Condition:
          #     StringNotLike:
          #       aws:Referer:
          #         - !Sub "${SecretReferer}"                  

          # - Action:
          #     - s3:GetObject
          #   Effect: Allow
          #   Resource:
          #     Fn::Join:
          #       - ""
          #       - - "arn:aws:s3:::"
          #         - Ref: "S3BucketForWebsiteContent"
          #         - "/*"
          #   Principal:
          #     CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  DNSRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          HostedZoneId: "Z2FDTNDATAQYW2" # this is a special value for a CloudFront ALIAS.  not hard coded
          DNSName: !GetAtt WebsiteDistribution.DomainName
      - Name: !Sub "www.${DomainName}"
        Type: CNAME
        TTL: '60'
        ResourceRecords:
        - !GetAtt WebsiteDistribution.DomainName          

  AutomationUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'AutomationUserPassword'

  AutomationUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'AutomationUser'

  AutomationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !GetAtt AutomationUser.Arn
          Action:
          - sts:AssumeRole

  AutomationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AutomationPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action:
          - cloudformation:DescribeStacks
          Effect: Allow
          Resource: !Sub "${AWS::StackId}"
        - Action:
          - s3:ListBucket
          Effect: Allow
          Resource: !Sub "${S3BucketForWebsiteContent.Arn}"
        - Action:
          - s3:ListObjectsV2
          - s3:PutObject
          - s3:DeleteObject
          Effect: Allow
          Resource: !Sub "${S3BucketForWebsiteContent.Arn}/*"
        - Action:
          - cloudfront:GetDistribution
          - cloudfront:CreateDistribution
          - cloudfront:UpdateDistribution          
          - cloudfront:CreateInvalidation
          Effect: Allow
          Resource: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteDistribution}"          
      Roles: [!Ref AutomationRole]
      Users: [!Ref AutomationUser]

Outputs:
  WebsiteBucketName:
    Description: The logical ID of the website bucket
    Value: !Ref S3BucketForWebsiteContent
  WebsiteBucketArn:
    Description: The Arn of the website bucket
    Value: !GetAtt S3BucketForWebsiteContent.Arn
  WebsiteBucketUrl:
    Description: The website URL of the website bucket
    Value: !GetAtt S3BucketForWebsiteContent.WebsiteURL
  CloudFrontDistributionId:
    Description: The CloudFront distribution id
    Value: !Ref WebsiteDistribution
  CloudFrontDistributionDomainName:
    Description: The CloudFront distribution domain name
    Value: !GetAtt WebsiteDistribution.DomainName
  CloudFrontDistributionURL:
    Description: The CloudFront distribution URL
    Value: !Sub "https://${WebsiteDistribution.DomainName}"
  CloudFrontLogsBucketName:
    Description: The logical ID of the CloudFront logs bucket
    Value: !Ref CloudFrontLogsBucket
  CloudFrontLogsBucketArn:
    Description: The Arn of the CloudFront logs bucket
    Value: !GetAtt CloudFrontLogsBucket.Arn
  ApexWebsiteURL:
    Description: The apex website URL
    Value: !Sub "https://${DomainName}"
  WwwWebsiteURL:
    Description: The www website URL
    Value: !Sub "https://www.${DomainName}"
  RoleId:
    Description: The logical ID of the IAM role
    Value: !Ref AutomationRole
  RoleArn:
    Description: The ARN of the IAM role
    Value: !GetAtt AutomationRole.Arn
  PolicyId:
    Description: The logical ID of the IAM policy
    Value: !Ref AutomationPolicy
  AccessKey:
    Value: !Ref 'AutomationUserAccessKey'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt AutomationUserAccessKey.SecretAccessKey
    Description: AWSSecretAccessKey of new user    